- defaults:
    link:
        relink: true

- clean: ['~']

- shell:
    - ["wget -O zshrc http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc", Downloading gmrl zshrc]
- link:
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.ideavimrc: ideavimrc
    ~/.zshrc.local: zshrc.local
    ~/.zshrc: zshrc
    ~/.config/terminator/config: config/terminator/config
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gdbinit : gdbinit
    ~/.radare2rc : radare2rc

- shell:
        - [git submodule update --init --recursive, Installing submodules]
          
