- defaults:
    link:
        relink: true

- clean: ['~']

- shell:
    - ["wget -O zshrc http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc", Downloading gmrl zshrc]
- link:
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.ideavimrc: ideavimrc
    ~/.zshrc.local: zshrc.local
    ~/.zshrc: zshrc
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gdbinit : gdbinit
    ~/.radare2rc : radare2rc
    ~/.tmux.conf : tmux.conf
    ~/.xinitrc : xinitrc
    ~/.config/terminator/config: 
        create: true
        path: config/terminator/config
    ~/.config/powerline/themes/powerline.json:
        create: true
        path: config/powerline/themes/powerline.json
    ~/.sage/init.sage:
        create: true
        path: init.sage

- shell:
        - [git submodule update --init --recursive, Installing submodules]
          
