- defaults:
    link:
        relink: true

- clean: ['~']

- shell:
    - ["wget -O zshrc http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc", Downloading gmrl zshrc]
- link:
    ~/.vim: vim
    ~/.vimrc: vimrc
    ~/.zshrc.local: zshrc.local
    ~/.zshrc: zshrc
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gdbinit : gdbinit
    ~/.tmux.conf : tmux.conf
    ~/.config/starship.toml:
        create: true
        path: config/starship.toml

- shell:
        - [git submodule update --init --recursive, Installing submodules]
          
